### ISSUE TITLE
Error during vagrant up

### ISSUE THREAD

**Issue by jgallias** [gsingh93/ctf-vm#7]
default: /home/vagrant/tools/xrop/src/libxdisasm/src/binutils/missing: line 81: makeinfo: command not found
    default: WARNING: 'makeinfo' is missing on your system.
    default:          You should only need it if you modified a '.texi' file, or
    default:          any other file indirectly affecting the aspect of the manual.
    default:          You might want to install the Texinfo package:
    default:          <http://www.gnu.org/software/texinfo/>
    default:          The spurious makeinfo call might also be the consequence of
    default:          using a buggy 'make' (AIX, DU, IRIX), in which case you might
    default:          want to install GNU make:
    default:          <http://www.gnu.org/software/make/>
    default: Makefile:541: recipe for target 'bfd.info' failed
    default: make[5]: Leaving directory '/home/vagrant/tools/xrop/src/libxdisasm/src/binutils/bfd/doc'
    default: make[5]: *** [bfd.info] Error 127
    default: Makefile:1641: recipe for target 'info-recursive' failed
    default: make[4]: Leaving directory '/home/vagrant/tools/xrop/src/libxdisasm/src/binutils/bfd'
    default: make[4]: *** [info-recursive] Error 1
    default: Makefile:20: recipe for target 'binutils-libs' failed
    default: make[3]: Leaving directory '/home/vagrant/tools/xrop/src/libxdisasm/src'
    default: make[3]: *** [binutils-libs] Error 2
    default: Makefile:4: recipe for target 'libxdis' failed
    default: make[2]: Leaving directory '/home/vagrant/tools/xrop/src/libxdisasm'
    default: make[2]: *** [libxdis] Error 2
    default: Makefile:13: recipe for target 'makelib' failed
    default: make[1]: Leaving directory '/home/vagrant/tools/xrop/src'
    default: make[1]: *** [makelib] Error 2
    default: Makefile:6: recipe for target 'xrp' failed
    default: make: *** [xrp] Error 2
`The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

**Comment by gsingh93** [comment]
Should be solved by https://github.com/gsingh93/ctf-vm/commit/5b2fe7ecdfa61788cb46fdda1826ea1de4e69b22 which adds the `texinfo` dependency. Not going to backport the patch to branches other than master at the moment, don't have time to test that.
